In [69]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score 

In [219]:
# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the index of the maximum value along the last axis
max_index = np.argmax(arr, axis=-1)
print(max_index)  # Output: [2 2] # return index 

[2 2]


In [46]:
def relu(x):
    return np.maximum(0, x)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()
    
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    return A

In [112]:
import numpy as np

class Layer:
    def __init__(self, input_units, output_units, activation_function=None):
        self.W = np.random.randn(input_units, output_units)
        self.b = np.zeros(output_units)
        self.activation_function = activation_function


    def forward(self, inputs):
        linear_output = np.dot(inputs, self.W) + self.b
        if self.activation_function is None:
            return linear_output
        else:
            return self.activation_function(linear_output)

class NeuralNetwork:
    def __init__(self):
        self.layers = []
        self.model_weights = []

    def add(self, layer):
        self.layers.append(layer)
        self.model_weights.append(layer.W)
        
    def predict_prob(self, input_data):
        results = []
        for data in input_data:
            output = data
            for layer in self.layers:
                output = layer.forward(output)
            results.append(output)
        return results 

    def predict(self, input_data):
        prob_predictions = self.predict_prob(input_data)
        return [np.argmax(prediction) for prediction in prob_predictions]


    def print_architecture(self):
        print("Model Architecture:")
        for i, layer in enumerate(self.layers):
            activation = layer.activation_function.__name__ if layer.activation_function else "None"
            print(f"Layer {i+1}: Units={layer.W.shape[1]}, Activation={activation}")

    def print_weights(self):
        print("Model Weights:")
        for i, w in enumerate(self.model_weights):
            print(f"Layer {i+1} shape : {w.shape} weights:")
            print(w)




In [115]:
# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the neural network model
model = NeuralNetwork()
model.add(Layer(input_units=4, output_units=8, activation_function=np.tanh))
model.add(Layer(input_units=8, output_units=3, activation_function=softmax))

# Train the model
# model.print_architecture()
# model.print_weights()

predictions = model.predict(X_train_scaled)
print(f"score {accuracy_score(y_train, predictions)} ")

score 0.2 


In [116]:
model.print_weights()

Model Weights:
Layer 1 shape : (4, 8) weights:
[[-0.2406914  -0.07201091  2.08552538  1.10167431 -1.5935723   0.37715589
  -0.93884909  1.6283409 ]
 [ 0.35340316  1.21976047 -1.7183836  -0.61187104 -0.66151798 -0.20618126
  -1.14938511  0.55955925]
 [-0.10584681 -1.06819845 -0.058289    1.9543166   0.81549015 -0.04878784
  -0.63052124  2.37605012]
 [ 0.47792198  0.13214079 -0.84742017  0.85303901 -0.21250345  0.47252642
  -0.3800675   0.7093456 ]]
Layer 2 shape : (8, 3) weights:
[[-0.73650837  0.28955239 -0.51660726]
 [-2.14144121 -1.4683716  -0.76596573]
 [ 1.23832387 -1.01284832 -0.11255719]
 [-2.4407433   0.14423682 -0.31519767]
 [ 0.96536389 -2.11591317 -0.80528611]
 [-0.15690533 -0.21890586 -0.47514513]
 [ 0.83808695  1.04044323 -0.63160727]
 [ 1.266472   -2.60651901 -0.93397102]]


In [127]:
model.model_weights[0].shape

(4, 8)

In [128]:
flat = model.model_weights[0].flatten().shape
flat 

(32,)

In [105]:
predictions 

[0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 0,
 2,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0]

In [90]:
for pred in model.predict_prob(X_train_scaled):
    print(np.sum(pred))

0.9999999999999999
1.0000000000000002
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
1.0000000000000002
1.0
1.0
0.9999999999999998
0.9999999999999999
0.9999999999999999
1.0
1.0
0.9999999999999999
1.0000000000000002
0.9999999999999999
1.0
0.9999999999999999
1.0
1.0
0.9999999999999999
1.0
0.9999999999999999
1.0
1.0
1.0
1.0000000000000002
0.9999999999999999
1.0
1.0000000000000002
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0000000000000002
1.0
0.9999999999999999
0.9999999999999999
0.9999999999999999
1.0
1.0000000000000002
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
0.9999999999999999
1.0000000000000002
1.0
1.0
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
0.9999999999999998
1.0
1.0
1.0
1.0
0.9999999999999999
1.0
1.0
0.9999999999999999
0.9999999999999999
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.9999999999999998
1.0
1.0
0.9999999999999999
0.9999999999999998
0.9999999999999999
1.0
1.0
0.9999999999999999
1.0


In [86]:
model.print_architecture()
model.print_weights()


Model Architecture:
Layer 1: Units=8, Activation=tanh
Layer 2: Units=3, Activation=softmax
Model Weights:
Layer 1 shape : (4, 8) weights:
[[ 1.67209413  1.7355264  -0.17269693  0.48716413 -1.02493943  0.5415314
  -1.52740397  0.22989785]
 [ 1.35357391  2.24527859 -0.18933673  0.38120461  0.61573458  0.67857867
   1.00943776  2.17781957]
 [ 0.61488576 -0.2765128  -0.90332782  0.82920521  0.26155297 -2.05896084
   1.50361966  0.61666664]
 [ 1.15456045 -0.07773724 -0.72351464  0.56616603  0.28026668  0.61589131
  -0.06100279 -0.87413014]]
Layer 2 shape : (8, 3) weights:
[[-2.68860142  0.63292395  0.3258483 ]
 [ 0.8528011   0.33809983  1.3953345 ]
 [ 0.56715481  0.81208824 -0.75270146]
 [-1.20914951  0.49920835 -1.84157291]
 [-1.52273799  0.27216054 -0.1288624 ]
 [-0.28052794  0.31696375 -0.20862618]
 [-0.21190064  0.93915489 -0.2299219 ]
 [ 1.00419449 -0.36745259  2.21128585]]


In [109]:
from sklearn.datasets import load_breast_cancer

# Load breast cancer dataset
data = load_breast_cancer()
X = data.data
y = data.target

# Split dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the neural network model
model2 = NeuralNetwork()
model2.add(Layer(input_units=X_train_scaled.shape[1], output_units=8, activation_function=np.tanh))
model2.add(Layer(input_units=8, output_units=4, activation_function=np.tanh))
model2.add(Layer(input_units=4, output_units=2, activation_function=softmax))

predictions = model2.predict(X_test_scaled)
# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.5701754385964912


In [111]:
predictions

[0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1]

In [110]:
model2.predict_prob(X_test_scaled)

[array([0.80908279, 0.19091721]),
 array([0.1416408, 0.8583592]),
 array([0.26193922, 0.73806078]),
 array([0.90149856, 0.09850144]),
 array([0.29685962, 0.70314038]),
 array([0.90630015, 0.09369985]),
 array([0.1408345, 0.8591655]),
 array([0.77654482, 0.22345518]),
 array([0.91727016, 0.08272984]),
 array([0.1038948, 0.8961052]),
 array([0.0664065, 0.9335935]),
 array([0.13765312, 0.86234688]),
 array([0.08614257, 0.91385743]),
 array([0.25653233, 0.74346767]),
 array([0.42247913, 0.57752087]),
 array([0.81654492, 0.18345508]),
 array([0.06741581, 0.93258419]),
 array([0.26452372, 0.73547628]),
 array([0.12960849, 0.87039151]),
 array([0.08690598, 0.91309402]),
 array([0.72913763, 0.27086237]),
 array([0.11978926, 0.88021074]),
 array([0.57909475, 0.42090525]),
 array([0.81468083, 0.18531917]),
 array([0.23217541, 0.76782459]),
 array([0.80453504, 0.19546496]),
 array([0.07170013, 0.92829987]),
 array([0.07312213, 0.92687787]),
 array([0.81420415, 0.18579585]),
 array([0.90639136, 0.